---
# playbook to get vSRX cloudformation facts
# default stackname can be overwritten with -e "stack_name=xxx" on cli
# global vars defined in group_vars/all/vars_file.yml

- name: Ansible CloudFormation
  hosts: localhost
  gather_facts: no
  vars: 
  tasks:
    - name: get CloudFormation stack {{ stack_name }} facts from AWS 
      cloudformation_facts:
        stack_name: "{{ stack_name }}"
        stack_resources: true
        region: eu-west-1

    # we need vSRXmanagementEIP info from ansible_facts.cloudformation.ansible-vsrx.stack_resources
    - name: Checking IP address of tag_Name_vSRXami
      debug: var=cloudformation['{{ stack_name }}']['stack_resources']['vSRXmanagementEIP']

    # no create var with IP of management address.
    # the can be done in group_vars stuff but we_re using nested var which took me an hour to find out
    # stack_name will now automatically be set to value of {{ stack_name }} 
    - name: set fact
      set_fact: 
        vSRX_group: "{{ cloudformation[stack_name]['stack_resources']['vSRXmanagementEIP'] }}"

    # for now we only have one vSRX, but looping trough array so we can have more vSRX in the future
    # as we have to localhost for our commands can't use seperate play
    # it can take some time to boot the vSRX so timeout should be set to couple of minutes
    - name: wait for vSRX to come online
      wait_for: port=22 host="{{ item }}" timeout=10
      with_items: "{{ vSRX_group }}"

    # now copy file using a raw method, no python on vSRX so we can't use copy module
    # file config file will only activate netconf and set root-authentication
    - name: copy file with some set commands using raw method
      raw: scp -i files/id984390-key.pem files/"{{ config_file }}" root@"{{ item }}":/cf/root
      with_items: "{{ vSRX_group }}"

    # now copy file using a raw method, no python on vSRX so we can't use copy module
    - name: copy file with shell script to configure vSRX 
      raw: scp -i files/id984390-key.pem files/"{{ shell_commands }}" root@"{{ item }}":/cf/root
      with_items: "{{ vSRX_group }}"

- name: Configure netconf on vSRX's
  hosts: tag_Name_vSRXami
  gather_facts: no
  tasks:
    # again, no python on vSRX so run /sbin/sh with shell_commands file to configure vSRX via raw module
    - name: run shell script to activate initial config
      raw: /sbin/sh/ /cf/root/"{{ shell_commands }}" >> /cf/root/output.txt
